steps:
# Step 1: Build and push Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-image'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/tasky-app:v1', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-image'
  args: ['push', 'gcr.io/${_PROJECT_ID}/tasky-app:v1']

# Step 2: Get GKE credentials
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get-credentials'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - '${_CLUSTER_NAME}'
  - '--zone=${_ZONE}'
  - '--project=${_PROJECT_ID}'

# Step 3: Create Kubernetes secret
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'create-secret'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    kubectl create secret generic mongodb-secret \
      --from-literal=uri="mongodb://admin:$$MONGODB_PASSWORD@$(gcloud compute instances describe mongodb-vm --zone=${_ZONE} --format='get(networkInterfaces[0].networkIP)'):27017/admin" \
      --dry-run=client -o yaml | kubectl apply -f -
  secretEnv: ['MONGODB_PASSWORD']

# Step 4: Deploy to Kubernetes
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'deploy-app'
  args:
  - 'apply'
  - '-f'
  - 'k8s-deployment.yaml'

substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _ZONE: us-central1-a
  _CLUSTER_NAME: tasky-cluster

availableSecrets:
  secretManager:
  - versionName: projects/${_PROJECT_ID}/secrets/mongodb-password/versions/latest
    env: 'MONGODB_PASSWORD'