steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'cleanup'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Cleaning up resources..."
    
    # Delete GKE cluster
    gcloud container clusters delete ${_CLUSTER_NAME} \
      --zone=${_ZONE} \
      --project=${PROJECT_ID} \
      --quiet || true

    # Delete MongoDB VM
    gcloud compute instances delete mongodb-vm \
      --zone=${_ZONE} \
      --project=${PROJECT_ID} \
      --quiet || true

    # Delete backup bucket
    gsutil rm -r gs://${_BACKUP_BUCKET} || true

    echo "Cleanup completed."

substitutions:
  _ZONE: us-central1-a
  _CLUSTER_NAME: tasky-cluster
  _BACKUP_BUCKET: ${PROJECT_ID}-mongodb-backups

options:
  logging: CLOUD_LOGGING_ONLY
